"""user_id in game not nullable

Revision ID: 85feba390bb6
Revises: 020dda3addee
Create Date: 2023-05-19 10:03:13.744373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85feba390bb6'
down_revision = '020dda3addee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Game', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Game', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
