"""message table

Revision ID: d6c5bad447d4
Revises: bc5124c13934
Create Date: 2023-05-12 19:05:28.803549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c5bad447d4'
down_revision = 'bc5124c13934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['Game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Message_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('Game', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('winner',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Game', schema=None) as batch_op:
        batch_op.alter_column('winner',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('Message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Message_timestamp'))

    op.drop_table('Message')
    # ### end Alembic commands ###
